import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider as JotaiProvider } from "jotai";
import Layout from "../layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tars Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`lg:p-[10px] p-[0px] ${inter.className}`}>
      <JotaiProvider>
        <Layout>
        {children}
        </Layout>
        </JotaiProvider>
        </body>
    </html>
  );
}
